### ISSUE TITLE
Change `rangeStrategy` for `python`

### ISSUE THREAD

**Issue by 34j** [browniebroke/pypackage-template#597]
**Is your feature request related to a problem? Please describe.**
I am frustrated when Renovate opens a PR that tries to shrink the Python version.
(e.g. >=3.8,<3.12 -> >=3.12,<3.13)

**Describe the solution you'd like**
I am not very familiar with Renovate, but I was wondering if this could be accomplished by setting the `rangeStrategy` to `widen` (only for `python`).
https://docs.renovatebot.com/configuration-options/#rangestrategy

**Additional context**
https://github.com/34j/cached-historical-data-fetcher/pull/17

**Comment by browniebroke** [comment]
Nice suggestion, I didn't know about that option. I never had this problem, maybe because I usually don't set an upper limit on my Python versions?

Could you try it on that repo and feedback how it goes? The default renovate config in `renovate.json` comes from my shared ones, they are on my renovate-configs repo. You can either add more options or completely replace it.

**Comment by 34j** [comment]
It was very easy.
```
{
  "extends": ["github>browniebroke/renovate-configs:python"],
  "packageRules": [
    {
      "matchPackageNames": ["python"],
      "rangeStrategy": "widen"
    }
  ]
}
```

**Comment by browniebroke** [comment]
Nice! [Added to my base config](https://github.com/browniebroke/renovate-configs/commit/59be1ebc056164bbe18e52d3e79954e4ea4ca354), let's see how it goes.
